config/routes.rb
Rails.application.routes.draw do
  get 'permission/index'

  root 'home#index'

  # Devise Routes
  devise_for :user, path: 'auth', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'register',
      sign_up: 'signup'
  }, controllers: {
      # :registrations => 'registrations',
      :sessions => 'sessions',
      #:omniauth_callbacks => 'omniauth_callbacks'
  }

  # routes
  resources :users, except: [:show] do
    get :change_password
    resources :permissions, except: [:show]
  end
  resources :sectors, except: [:show] do
    get :actions
  end
  resources :keypasses, except: [:show]
  resources :students, except: [:show] do
    get :import_xls, to: 'students#send_xls', on: :collection
    post :import_xls, to: 'students#import_xls', on: :collection
  end
  resources :courses, except: [:show]
  resources :incidents do
    get :sign, to: 'incidents#confirmation'
    post :sign, to: 'incidents#sign'
  end
  resources :report_incidents, only: [:new, :create]
  resources :positions, except: [:show]
  resources :patients, except: [:show] do
    resources :appointments, except: [:show], controller: 'patients/appointments'
  end
end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id                  :integer          not null, primary key
#  name                :string
#  course_id           :integer
#  photo               :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  responsible         :string
#  responsible_contact :string
#  contact             :string
#  ra                  :integer
#  password            :string
#  password_digest     :string
#  enrollment          :string
#  cpf                 :string
#  birth_date          :date
#  course_situation    :integer
#

class Student < ApplicationRecord
  has_secure_password

  mount_uploader :photo, StudentUploader
  include SearchCop

  enum course_situation: [
    'Egresso', 'Falecido', 'Trancado', 'Transferido Externamente',
    'Transferido Internamente', 'Em curso', 'Evadido', 'Desligado',
    'Regime Domiciliar', 'Integralizado em fase escolar',
    'Concluído', 'Enriquecimento Curricular', 'Em mobilidade acadêmica',
    'Reprovado', 'Aluno Especial'
  ]

  delegate :name, to: :course, prefix: true
  delegate :initial, to: :course, prefix: true

  # Validações
  validates :name, :course, :ra, presence: true

  # Associações
  belongs_to :course

  # Atributos para busca com SearchCop
  search_scope :search do
    attributes :name
    attributes :course => "course.name"
    attributes :initial => "course.initial"
  end

  # Retorna um vetor contendo os nomes e seus respectivos IDs
  #
  # @return [Array] contendo nomes e seus IDs
  def self.get_all
    order('name asc').collect {|p| [ p.name, p.id ] }
  end

  def self.import(attributes, course)
    student = find_by_ra(attributes[2]) || new
    student.assign_attributes(set_attributes(student, course, attributes))
    student.save
  end

  # Retorna um vetor com os atributos que serão utilizados para a
  # busca nas listagens dos estudantes
  #
  # @return [Array] contendo os atributos para a busca
  def self.ordenation_attributes
    [["ID",'id'], ["Nome",'name']]
  end

  private

  def self.set_attributes(student, course, attributes)
    params = {
      name: attributes[3],
      course: course,
      contact: attributes[6],
      ra: attributes[2].to_i,
      enrollment: attributes[1],
      cpf: attributes[4],
      birth_date: attributes[5],
      course_situation: attributes[7]
    }
    check_password(student, params)
  end

  def self.check_password(student, params)
    if student.password.nil?
      params['password'] = rand(11111111..99999999).to_s
      params
    else
      params
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  include ParamsSearch

  load_and_authorize_resource

  before_action :set_student, only: [:edit, :destroy, :update]
  add_breadcrumb "Home", :root_path

  def index
    add_breadcrumb "Diren", sector_actions_path('diren')
    add_breadcrumb "Estudantes"

    @students = Student.order("#{set_order}": :desc)
                       .search(params[:search])
                       .page(params[:page]).per(set_amount_return)
  end

  def new
    add_breadcrumb "Diren", sector_actions_path('diren')
    add_breadcrumb "Estudantes", :students_path
    add_breadcrumb "Novo estudante"

    @students = Student.new
  end

  def create
    @students = Student.new(student_params)
    if @students.save
      redirect_to students_path, flash: { success: 'Estudante cadastro com sucesso' }
    else
      flash.now[:error] = @students.errors.full_messages
      render :new
    end
  end

  def edit
    add_breadcrumb "Diren", sector_actions_path('diren')
    add_breadcrumb "Estudantes", :users_path
    add_breadcrumb "Atualizar estudante"
  end

  def update
    if @student.update(check_password(student_params))
      redirect_to students_path, flash: { success: 'Estudante atualizado com sucesso' }
    else
      flash.now[:error] = @student.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @student.destroy
      flash[:success] = "Estudante deletado com sucesso"
      redirect_back(fallback_location: students_path)
    else
      flash.now[:error] = @student.errors.full_messages
      render :new
    end
  end

  def send_xls
  end

  def import_xls
    course = Course.find(params[:course])
    book = Spreadsheet.open params[:xls].tempfile.path
    students_attributes = book.worksheet 0
    students_attributes.each 1 do |attributes|
      Student.import(attributes, course)
    end
    redirect_to students_path
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def check_password(user_params)
    if user_params[:password].empty?
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
      user_params
    else
      user_params
    end
  end

  def student_params
    params.require(:student).permit(
      :name, :photo, :course_id, :responsible, :responsible_contact, :contact,
      :password, :password_confirmation, :ra, :cpf, :course_situation,
      :enrollment
    )
  end
end

app/views/students/_form.html.erb
<%= form_for student do |f| %>
  <fieldset>
    <legend>Dados pessoais</legend>
    <div class="field is-horizontal">
      <div class="field-body">
        <div class="field">
          <p class="control">
            <%= f.label :name, "Nome", class: 'label' %>
            <%= f.text_field :name, class: 'input is-medium', placeholder: 'Nome', required: true %>
          </p>
        </div>
        <div class="field">
          <%= f.label :photo, 'Imagem', class: 'label' %>
          <div class="file is-medium is-success">
            <label class="file-label">
              <%= f.file_field :photo, class: 'file-input' %>
              <span class="file-cta">
                <span class="file-icon">
                  <i class="fa fa-upload"></i>
                </span>
                <span class="file-label">
                  Selecione a foto do estudante
                </span>
              </span>
            </label>
          </div>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-body">

        <div class="field">
          <p class="control">
            <%= f.label :cpf, "CPF", class: 'label' %>
            <%= f.text_field :cpf, class: 'input is-medium cpf', placeholder: 'CPF', required: true %>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <%= f.label :birth_date, "Data de Nascimento", class: 'label' %>
            <%= f.text_field :birth_date, class: 'input is-medium date', value: extract_and_format_date(student.birth_date), placeholder: 'Data de Nascimento', required: true %>
          </p>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-body">
        <div class="field">
          <p class="control">
            <%= f.label :password, "Senha para assinatura digital", class: 'label' %>
            <%= f.password_field :password, class: 'input is-medium' %>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <%= f.label :password_confirmation, "Confirmar senha", class: 'label' %>
            <%= f.password_field :password_confirmation, class: 'input is-medium' %>
          </p>
        </div>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Dados responsável</legend>
    <div class="field is-horizontal">
      <div class="field-body">
        <div class="field">
          <p class="control">
            <%= f.label :responsible, "Nome", class: 'label' %>
            <%= f.text_field :responsible, class: 'input is-medium', placeholder: 'Responsável' %>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <%= f.label :responsible_contact, "Contato", class: 'label' %>
            <%= f.text_field :responsible_contact, class: 'input is-medium', placeholder: 'Email / Telefone' %>
          </p>
        </div>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Dados do Curso/Turma</legend>
    <div class="field is-horizontal">
      <div class="field-body">
        <div class="field">
          <p class="control">
            <%= f.label :ra, "R.A", class: 'label' %>
            <%= f.text_field :ra, class: 'input is-medium', placeholder: 'R.A', required: true %>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <%= f.label :enrollment, "Matrícula", class: 'label' %>
            <%= f.text_field :enrollment, class: 'input is-medium', placeholder: 'Matrícula', required: true %>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <%= f.label :course_id, "Curso", class: 'label' %>
            <span class="select is-medium">
              <%= f.select :course_id, Course.initials, {}, { :class => "select2" } %>
            </span>
          </p>
        </div>
        <div class="field">
          <%= f.label :course_situation, 'Situação do curso', class: 'label' %>
          <p class="control">
            <span class="select">
              <%= f.select :course_situation, Student.course_situations.keys.to_a, {}, { :class => "select2 is-medium" } %>
            </span>
          </p>
        </div>
      </div>
    </div>
  </fieldset>

  <div class="margin-top-20px">
    <p class="control">
      <%= f.submit "Salvar", class: "button is-success is-medium in-mobile-expand"%>
    </p>
  </div>
<% end %>

app/views/students/_form_sign.html.erb
<%= form_for incident, method: :post, url: incident_sign_path(incident, id: incident) do |f| %>
  <fieldset>
    <legend>Dados para autenticação</legend>
    <div class="field is-horizontal">
      <div class="field-body">
        <div class="field">
          <p class="control">
            <%= f.label :ra, "R.A", class: 'label' %>
            <%= f.text_field :ra, class: 'input is-medium', placeholder: 'R.A', value: incident.student.ra, disabled: true  %>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <%= f.label :password, "Senha", class: 'label' %>
            <%= f.password_field :password, class: 'input is-medium' %>
          </p>
        </div>
      </div>
    </div>
  </fieldset>

  <div class="margin-top-20px">
    <p class="control">
      <%= f.submit "Assinar", class: "button is-success is-medium in-mobile-expand"%>
    </p>
  </div>
<% end %>

app/views/students/_form_xls.html.erb
<%= form_with do |f| %>
  <fieldset>
    <legend>Arquivo XLS</legend>
    <div class="field">
      <div class="field">
        <div class="field">
          <p class="control">
            <%= f.label :course, "Curso", class: 'label' %>
            <span class="select is-medium">
              <%= f.select :course, Course.initials, {}, {} %>
            </span>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <%= f.label :xls, "Arquivo XLS", class: 'label' %>
            <%= f.file_field :xls, class: 'input is-medium', placeholder: 'R.A'  %>
          </p>
        </div>
      </div>
    </div>
  </fieldset>

  <div class="margin-top-20px">
    <p class="control">
      <%= f.submit "Importar", class: "button is-success is-medium in-mobile-expand"%>
    </p>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="content">
  <h1 class="title is-3">Editar estudante</h1>
  <%= render 'form', student: @student %>
</div>

app/views/students/index.html.erb
<div class="columns">
  <div class="column no-print">
    <% if can? :create, Student %>
      <%= link_to new_student_path, class: "button is-success in-mobile-expand" do %>
        <span class="icon">
          <i class="ion-plus-round"></i>
        </span>
        <span>Novo Estudante</span>
      <% end %>
    <% end %>
    <% if current_user.admin? %>
      <%= link_to import_xls_students_path, class: "button is-success in-mobile-expand" do %>
        <span class="icon">
          <i class="ion-ios-upload-outline"></i>
        </span>
        <span>Importar xls</span>
      <% end %>
    <% end %>
  </div>
  <div class="column no-print">
    <% show_search_error_message(@students, params) %>
    <%= render 'layouts/search', path: students_path, v: attr_order(@students) %>
  </div>
</div>

<table class="table is-striped is-fullwidth">
  <thead>
    <tr>
      <th>ID</th>
      <th>Foto</th>
      <th>Nome</th>
      <th class="is-hidden-mobile">Curso</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
    <tr>
      <td><%= student.id %></td>
      <td><%= image_tag student&.photo.thumb %></td>
      <td><%= student.name %></td>
      <td class="is-hidden-mobile"><%= student.course_initial %></td>
      <td class="has-text-right no-print">
        <div class="dropdown">
          <span class="button is-danger in-mobile-expand">Ações</span>
          <div class="dropdown-content">
            <% if can? :update, Student %>
              <%= link_to edit_student_path(student), class: 'button is-success in-mobile-expand' do %>
                <span class="icon">
                  <i class="ion-edit"></i>
                </span>
                <span>Editar</span>
              <% end %>
            <% end %>
            <% if can? :destroy, Student %>
              <%= link_to student_path(student), method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class: 'button is-danger in-mobile-expand' do %>
                <span class="icon">
                  <i class="ion-close"></i>
                </span>
                <span>Excluir</span>
              <% end %>
            <% end %>
          </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @students %>
<br />

app/views/students/new.html.erb
<div class="content">
  <h1 class="title is-3">Cadastrar estudante</h1>
  <%= render 'form', student: @student %>
</div>

app/views/students/send_xls.html.erb
<div class="content">
  <h1 class="title is-3">Importar estudantes via XLS</h1>
  <p>
    CUIDADO: Ao importar um novo arquivo, o mesmo deve seguir o modelo disponível neste <a href="#">link</a><br>
    Não importe arquivos fora deste padrão
  </p>
  <%= render 'students/form_xls' %>
</div>