config/routes.rb
Rails.application.routes.draw do
  get 'permission/index'

  root 'home#index'

  # Devise Routes
  devise_for :user, path: 'auth', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'register',
      sign_up: 'signup'
  }, controllers: {
      # :registrations => 'registrations',
      :sessions => 'sessions',
      #:omniauth_callbacks => 'omniauth_callbacks'
  }

  # routes
  resources :users, except: [:show] do
    get :change_password
    resources :permissions, except: [:show]
  end
  resources :sectors, except: [:show] do
    get :actions
  end
  resources :keypasses, except: [:show]
  resources :students, except: [:show] do
    get :import_xls, to: 'students#send_xls', on: :collection
    post :import_xls, to: 'students#import_xls', on: :collection
  end
  resources :courses, except: [:show]
  resources :incidents do
    get :sign, to: 'incidents#confirmation'
    post :sign, to: 'incidents#sign'
  end
  resources :report_incidents, only: [:new, :create]
  resources :positions, except: [:show]
  resources :patients, except: [:show] do
    resources :appointments, except: [:show], controller: 'patients/appointments'
  end
end

app/models/incident.rb
# == Schema Information
#
# Table name: incidents
#
#  id            :integer          not null, primary key
#  student_id    :integer
#  user_id       :integer
#  institution   :integer
#  description   :text
#  date_incident :date
#  soluction     :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  course_id     :integer
#  time_incident :time
#  assistant_id  :integer
#  signed_in     :datetime
#  is_resolved   :integer
#  type_student  :integer
#  sanction      :integer
#  school_group  :integer
#

class Incident < ApplicationRecord
  include SearchCop

  validates :user, :course, :assistant, :institution, :description,
	          :date_incident, :time_incident, presence: true

  enum institution: ['Ifms', 'Ufms', 'Cemid']
  enum is_resolved: ['no_', 'yes_']
  enum type_student: ['non_resident', 'resident']
  enum school_group: [
    '1A', '1B', '2A', '2B', '3A', '3B', '4A', '4B', '5A', '5B', '6A', '6B',
    '7A', '7B', '8A', '8B', '9A', '9B', '10A', '10B'
  ]
  enum sanction: [
    'verbal_warning',
    'written_warning',
    'suspension',
    'quitting_school'
  ]

  belongs_to :student, optional: true
  belongs_to :user
  belongs_to :course, optional: true
  belongs_to :assistant, class_name: 'User', foreign_key: 'assistant_id'

  # Atributos para busca com SearchCop
  search_scope :search do
    attributes student: "student.id"
    attributes course: "course.id"
    attributes student_name: "student.name"
    attributes course_name: "course.name"
    attributes institution: "institution"
    attributes type_student: "type_student"
    attributes date_incident: "date_incident"
  end

  def student_name
    student.present? ? student.name : " ---- "
  end

  def course_initial
    course.present? ? course.initial : " ---- "
  end

  def signed_by_student_in
    signed_in.strftime('%d/%m/%Y') if signed_in.present?
  end

  # Retorna um vetor com os atributos que serão utilizados para a
  # busca nas listagens de ocorrencias
  #
  # @return [Array] contendo os atributos para a busca
  def self.ordenation_attributes
    [["ID",'id'], ["Estudante",'student_id'], ["Instituição",'institution'],
     ["Data",'date_incident'], ["Turma",'course_id']]
  end
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  include ParamsSearch

  load_and_authorize_resource

  before_action :set_incident, only: [
    :edit, :destroy, :update, :confirmation, :sign, :show
  ]

  add_breadcrumb "Home", :root_path

  def index
    add_breadcrumb "Diren", sector_actions_path('diren')
    add_breadcrumb "Ocorrências"

    @incidents = Incident.order("#{set_order}": :desc)
                         .search(params[:search])
                         .page(params[:page]).per(set_amount_return)
  end

  def new
    add_breadcrumb "Diren", sector_actions_path('diren')
    add_breadcrumb "Ocorrências", :incidents_path
    add_breadcrumb "Nova ocorrências"

    @incidents = Incident.new
  end

  def create
    @incident = Incident.new(incident_params)
    @incident.user = current_user
    if @incident.save
      send_email_to(@incident&.course&.coordinator&.email)
      redirect_to incidents_path, flash: { success: 'Ocorrência cadastra com sucesso' }
    else
      flash.now[:error] = @incident.errors.full_messages
      render :new
    end
  end

  def edit
    add_breadcrumb "Diren", sector_actions_path('diren')
    add_breadcrumb "Ocorrências", :incidents_path
    add_breadcrumb "Atualizar Ocorrência"
  end

  def update
    if @incident.update(incident_params)
      redirect_to incidents_path, flash: { success: 'Ocorrência atualizada com sucesso' }
    else
      flash.now[:error] = @incident.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @incident.destroy
      flash[:success] = "Ocorrência deletada com sucesso"
      redirect_back(fallback_location: incidents_path)
    else
      flash.now[:error] = @incident.errors.full_messages
      render :new
    end
  end

  def show
    add_breadcrumb "Diren", sector_actions_path('diren')
    add_breadcrumb "Ocorrências", :incidents_path
    add_breadcrumb "visualizar ocorrência"
  end

  ## Mostra a confirmação para que o estudante possa assinar
  def confirmation
    if @incident.student.ra.nil?
      flash.now[:error] = "Por favor, cadastre uma senha e um R.A para o estudante"
      redirect_to incidents_path
    end
  end

  # Por meio de um usuário RA e senha
  # o estudante assina a ocorrência dando ciencia do fato
  def sign
    if @incident.student.authenticate(params[:incident]['password'])
      if @incident.update(signed_in: Time.zone.now)
        redirect_to incidents_path, flash: { success: 'Ocorrência assinada com sucesso' }
      end
    else
      flash.now[:error] = "Sua senha esta incorreta"
      render :confirmation
    end
  end

  private

  def send_email_to(coordinator)
    unless Rails.env.test?
      InsidentMailer.send_mailer(coordinator).deliver_now
    end
  end

  def set_incident
    if params[:id]
      @incident = Incident.find(params[:id])
    else
      @incident = Incident.find(params[:incident_id])
    end
  end

  def incident_params
    params.require(:incident).permit(
      :student_id, :course_id, :date_incident, :assistant_id, :time_incident,
      :institution, :description, :soluction, :is_resolved, :type_student,
      :sanction, :school_group
    )
  end
end

app/views/incidents/_form.html.erb
<%= form_for model do |f| %>
  <fieldset>
    <legend>Dados do estudante</legend>
    <div class="columns">
      <div class="column">
        <div class="field">
          <%= f.label :student_id, 'Estudante', class: 'label' %>
          <p class="control">
            <div class="select">
              <%= f.select :student_id, Student.get_all, { prompt: "Selecione o estudante" }, { :class => "select2 is-medium" } %>
            </div>
          </p>
        </div>
        <div class="field">
          <%= f.label :course_id, 'Curso', class: 'label' %>
          <p class="control">
            <span class="select">
              <%= f.select :course_id, Course.names, { prompt: "Selecione o Curso" }, { :class => "select2 is-medium" } %>
            </span>
          </p>
        </div>
        <div class="field">
          <%= f.label :school_group, 'Turma', class: 'label' %>
          <p class="control">
            <span class="select">
              <%= f.select :school_group, Incident.school_groups.keys.to_a, { prompt: "Selecione a Turma" }, { :class => "select select2 is-medium" } %>
            </span>
          </p>
        </div>
        <div class="field">
          <%= f.label :type_student, 'Estudente é?', class: 'label' %>
          <p class="control">
            <span class="select">
              <%= f.select :type_student, human_enum_name('incident.type_student', Incident.type_students.keys), {}, { :class => "select select2 is-medium" } %>
            </span>
          </p>
        </div>
      </div>
      <div class="column has-text-centered">
        <% if !model.student&.photo.nil? %>
          <%= link_to model.student.photo.to_s, class: 'fancybox' do %>
            <%= image_tag model.student.photo.thumb %>
            <p>Clique para ampliar</p>
          <% end %>
        <% end %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Dados do assistente</legend>
    <div class="field is-horizontal">
      <div class="field-body">
        <div class="field">
          <%= f.label :assistant_id, 'Assistente', class: 'label' %>
          <p class="control">
            <span class="select">
              <%= f.select :assistant_id, User.get_all, {}, { :class => "select select2 is-medium" } %>
            </span>
          </p>
        </div>
        <div class="field">
          <%= f.label :institution, 'Instituição', class: 'label' %>
          <p class="control">
            <span class="select">
              <%= f.select :institution, Incident.institutions.keys.to_a, {}, { :class => "select select2 is-medium" } %>
            </span>
          </p>
        </div>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Ocorrência</legend>
    <div class="field is-horizontal">
      <div class="field-body">
        <div class="field">
          <p class="control">
            <%= f.label :date_incident, 'Data ocorrência', class: 'label' %>
            <%= f.text_field :date_incident, class: 'input is-medium date', value: extract_and_format_date(model.date_incident), placeholder: 'Data ocorrência', required: true %>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <%= f.label :time_incident, 'Hora ocorrência', class: 'label' %>
            <%= f.text_field :time_incident, class: 'input is-medium time', value: extract_and_format_time(model.time_incident), placeholder: 'Hora ocorrência', required: true %>
          </p>
        </div>
      </div>
    </div>
    <div class="field">
      <div class="field">
        <p class="control">
          <%= f.label :description, 'Ocorrência', class: 'label' %>
          <%= f.text_area :description, class: 'textarea is-medium', placeholder: 'Ocorrência' %>
        </p>
      </div>
    </div>
    <% if current_user.it_is_part_of_the_sector?('diren', 'serti') %>
      <div class="field is-horizontal">
        <div class="field-body">
          <div class="field">
            <%= f.label :sanction, 'Sanção aplicada', class: 'label' %>
            <p class="control">
              <span class="select">
                <%= f.select :sanction, human_enum_name('incident.sanction', Incident.sanctions.keys), { prompt: "Sanção aplicada" }, { :class => "select2 select is-medium" } %>
              </span>
            </p>
          </div>
          <% if current_user.it_is_part_of_the_sector?('diren', 'serti') %>
          <div class="field">
            <%= f.label :is_resolved, 'Ocorrências resolvida?', class: 'label' %>
            <p class="control">
              <span class="select">
                <%= f.select :is_resolved, human_enum_name('incident.is_resolved', Incident.is_resolveds.keys), {}, { :class => "is-medium" } %>
              </span>
            </p>
          </div>
          <% end %>
          <div class="field">
            <p class="control padding-top-40">
              <a href="http://www.ifms.edu.br/wp-content/uploads/2016/04/Anexo_Resolução-001_2017_Regulamento-Disciplinar-Discente-Atualização.pdf" target="_blank">Acesse aqui o Regulamento Disciplinar Discente</a>
            </p>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="field">
          <p class="control">
            <%= f.label :soluction, 'Descrição da solução', class: 'label' %>
            <%= f.text_area :soluction, class: 'textarea is-medium', placeholder: 'Solução' %>
          </p>
        </div>
      </div>
    <% end %>
  </fieldset>

  <div class="margin-top-20px">
    <p class="control">
      <%= f.submit "Salvar", class: "button is-success is-medium in-mobile-expand"%>
    </p>
  </div>
<% end %>

app/views/incidents/confirmation.html.erb
<div class="content">
  <h1 class="title is-3">Assinar ocorrência</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <div><b>Nome do estudante:</b> <%= @incident.student_name %></div>
    <div><b>Curso/Turma:</b> <%= @incident.course.name %></div>
    <div>
      <b>Data/Hora ocorrência</b>
      <%= extract_and_format_date @incident.date_incident  %> ás
      <%= extract_and_format_time @incident.time_incident  %>
    </div>
    <div><b>Local:</b> <%= @incident.course.name %></div>
    <br>
    <%= render 'students/form_sign', incident: @incident %>
</div>

app/views/incidents/edit.html.erb
<div class="content">
  <h1 class="title is-5">Atualizar ocorrência</h1>
  <%= render 'form', model: @incident %>
</div>

app/views/incidents/index.html.erb
<div class="columns">
  <div class="column">
    <% if can? :create, Incident %>
      <%= link_to new_incident_path, class: "button is-success in-mobile-expand" do %>
        <span class="icon">
          <i class="ion-plus-round"></i>
        </span>
        <span>Nova ocorrência</span>
      <% end %>
    <% end %>
  </div>
  <div class="column">
    <% show_search_error_message(@incidents, params) %>
    <%= render 'layouts/search', path: incidents_path, v: attr_order(@incidents) %>
  </div>
</div>

<table class="table is-striped is-fullwidth">
  <thead>
    <tr>
      <th>ID</th>
      <th>Data</th>
      <th>Estudante</th>
      <th>Turma</th>
      <th>Instituição</th>
      <th>Assinado?</th>
      <th>Verificado?</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @incidents.each do |incident| %>
    <tr>
      <td><%= incident.id %></td>
      <td><%= extract_and_format_date(incident.date_incident) %></td>
      <td><%= incident.student_name %></td>
      <td><%= incident.course_initial %></td>
      <td><%= incident.institution %></td>
      <td class="has-text-centered"><%= verificated?(incident.signed_in?).html_safe %></td>
      <td class="has-text-centered"><%= verificated?(incident.read_attribute_before_type_cast(:is_resolved)).html_safe %></td>
      <td class="has-text-right">
        <div class="dropdown">
          <span class="button is-danger in-mobile-expand">Ações</span>
          <div class="dropdown-content">
            <% if can? :read, Incident %>
              <%= link_to incident_path(incident), class: 'button is-success in-mobile-expand' do %>
                <span class="icon">
                  <i class="ion-search"></i>
                </span>
                <span>Visualizar</span>
              <% end %>
            <% end %>
            <% if can? :confirmation, Incident %>
              <% if incident.signed_in.nil? && !incident.student.nil? %>
                <%= link_to incident_sign_path(incident), class: 'button' do %>
                  <span class="icon">
                    <i class="ion-document-text"></i>
                  </span>
                  <span>Assinar</span>
                <% end %>
              <% end %>
            <% end %>
            <% if can? :update, Incident %>
              <%= link_to edit_incident_path(incident), class: 'button is-success' do %>
                <span class="icon">
                  <i class="ion-edit"></i>
                </span>
                <span>Editar</span>
              <% end %>
            <% end %>
            <% if can? :destroy, Incident %>
              <%= link_to incident_path(incident), method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class: 'button is-danger' do %>
                <span class="icon">
                  <i class="ion-close"></i>
                </span>
                <span>Excluir</span>
              <% end %>
            <% end %>
          </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="modal">
  <div class="modal-background"></div>
  <div class="modal-content">
    <!-- Any other Bulma elements you want -->
  </div>
  <button class="modal-close is-large"></button>
</div>

<%= paginate @incidents %>

app/views/incidents/new.html.erb
<div class="content">
  <h1 class="title is-3">Cadastrar ocorrência</h1>
  <%= render 'form', model: @incident %>
</div>

app/views/incidents/show.html.erb
<div class="content">
  <h1 class="title is-3">Ocorrência N#<%= @incident.id %></h1>
  <div class="content">
    <p><b><%= @incident&.student&.name %></b></p>
    <p><b><%= @incident&.course&.name %> / <%= @incident&.school_group %></b></p>
    <% if @incident&.student&.responsible.present? %>
    <p><b>Responsável:</b> <%= @incident&.student&.responsible %> / <%= @incident&.student&.responsible_contact %> </p>
    <% end %>
    <p> Data ocorrência: <b><%= extract_and_format_date(@incident&.date_incident) %> às <%= extract_and_format_time(@incident&.time_incident) %></b></p>
    <p> Local: <b><%= @incident.institution.upcase %></b></p>
    <p> Assinado digitalmente em: <b><%= @incident.signed_by_student_in %></b></p>
  </div>
  <div class="content">
    <p><b>Problema ocorrido</b></p>
    <p><%= @incident&.description %></p>
    <% if @incident&.sanction.present? %>
    <p><b>Solução adoata para o problema</b></p>
    <p><b>Sanção adota:</b> <%= I18n.t("activerecord.attributes.incident.sanction.#{@incident&.sanction}") %></p>
    <p><%= @incident&.soluction %></p>
    <% end %>
  </div>
</div>