config/routes.rb
Rails.application.routes.draw do
  get 'permission/index'

  root 'home#index'

  # Devise Routes
  devise_for :user, path: 'auth', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'register',
      sign_up: 'signup'
  }, controllers: {
      # :registrations => 'registrations',
      :sessions => 'sessions',
      #:omniauth_callbacks => 'omniauth_callbacks'
  }

  # routes
  resources :users, except: [:show] do
    get :change_password
    resources :permissions, except: [:show]
  end
  resources :sectors, except: [:show] do
    get :actions
  end
  resources :keypasses, except: [:show]
  resources :students, except: [:show] do
    get :import_xls, to: 'students#send_xls', on: :collection
    post :import_xls, to: 'students#import_xls', on: :collection
  end
  resources :courses, except: [:show]
  resources :incidents do
    get :sign, to: 'incidents#confirmation'
    post :sign, to: 'incidents#sign'
  end
  resources :report_incidents, only: [:new, :create]
  resources :positions, except: [:show]
  resources :patients, except: [:show] do
    resources :appointments, except: [:show], controller: 'patients/appointments'
  end
end

app/models/sector.rb
# == Schema Information
#
# Table name: sectors
#
#  id         :integer          not null, primary key
#  name       :string
#  initial    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#  icon       :string
#

class Sector < ApplicationRecord
  extend FriendlyId
  friendly_id :initial, use: :slugged

  # Validações
  validates :name, :initial, presence: true

  # Associações
  has_many :users

  # Retorna um vetor contendo as iniciais e seus respectivos IDs
  #
  # @return [Array] contendo as inicias e seus IDs
  def self.initials
    all.collect {|p| [ p.initial, p.id ] }
  end
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  add_breadcrumb "Home", :root_path

  def actions
    add_breadcrumb "#{params[:sector_id].upcase}"
    render params[:sector_id]
  end
end

app/views/sectors/assal.html.erb
<div class="columns is-multiline shortcuts">
  <% if can? :read, Incident %>
    <div class="column is-one-quarter">
      <%= link_to incidents_path do %>
        <section>
          <i class="fa fa-book icons"></i>
          <h1>Ocorrências</h1>
        </section>
      <% end %>
    </div>
  <% end %>
</div>

app/views/sectors/audi.html.erb
<div class="columns is-multiline shortcuts">
  <% if can? :read, Student %>
  <div class="column is-one-quarter">
    <%= link_to students_path do %>
      <section>
        <i class="ion-ios-people-outline"></i>
        <h1>Estudantes</h1>
      </section>
    <% end %>
  </div>
  <% end %>
</div>

app/views/sectors/diren.html.erb
<div class="columns is-multiline shortcuts">
  <% if can? :read, Student %>
  <div class="column is-one-quarter">
    <%= link_to students_path do %>
      <section>
        <i class="ion-ios-people-outline"></i>
        <h1>Estudantes</h1>
      </section>
    <% end %>
  </div>
  <% end %>

  <% if can? :read, Course %>
  <div class="column is-one-quarter">
    <%= link_to courses_path do %>
      <section>
        <i class="fa fa-university icons"></i>
        <h1>Cursos</h1>
      </section>
    <% end %>
  </div>
  <% end %>

  <% if can? :read, Incident %>
  <div class="column is-one-quarter">
    <%= link_to incidents_path do %>
      <section>
        <i class="fa fa-book icons"></i>
        <h1>Ocorrências</h1>
      </section>
    <% end %>
  </div>
  <% end %>
</div>

app/views/sectors/prof.html.erb
<div class="columns is-multiline shortcuts">
  <% if can? :read, Student %>
  <div class="column is-one-quarter">
    <%= link_to students_path do %>
      <section>
        <i class="ion-ios-people-outline"></i>
        <h1>Estudantes</h1>
      </section>
    <% end %>
  </div>
  <% end %>
</div>

app/views/sectors/serti.html.erb
<div class="columns shortcuts">
  <% if can? :read, User %>
  <div class="column">
    <%= link_to users_path do %>
      <section>
        <i class="ion-ios-people-outline"></i>
        <h1>Usuários</h1>
      </section>
    <% end %>
  </div>
  <% end %>

  <% if can? :read, Keypass %>
  <div class="column">
    <%= link_to keypasses_path do %>
      <section>
        <i class="ion-ios-locked-outline"></i>
        <h1>Senhas</h1>
      </section>
    <% end %>
  </div>
  <% end %>

  <% if can? :read, Position %>
  <div class="column">
    <%= link_to positions_path do %>
      <section>
        <i class="ion-android-people"></i>
        <h1>Cargos/Funçôes</h1>
      </section>
    <% end %>
  </div>
  <% end %>

  <div class="column">
  </div>
</div>

app/views/sectors/teclabinfo.html.erb
<div class="columns is-multiline shortcuts">
  <% if can? :read, Keypass %>
  <div class="column is-one-quarter">
    <%= link_to keypasses_path do %>
      <section>
        <i class="ion-ios-locked-outline"></i>
        <h1>Senhas</h1>
      </section>
    <% end %>
  </div>
  <% end %>
</div>