config/routes.rb
Rails.application.routes.draw do
  get 'permission/index'

  root 'home#index'

  # Devise Routes
  devise_for :user, path: 'auth', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'register',
      sign_up: 'signup'
  }, controllers: {
      # :registrations => 'registrations',
      :sessions => 'sessions',
      #:omniauth_callbacks => 'omniauth_callbacks'
  }

  # routes
  resources :users, except: [:show] do
    get :change_password
    resources :permissions, except: [:show]
  end
  resources :sectors, except: [:show] do
    get :actions
  end
  resources :keypasses, except: [:show]
  resources :students, except: [:show] do
    get :import_xls, to: 'students#send_xls', on: :collection
    post :import_xls, to: 'students#import_xls', on: :collection
  end
  resources :courses, except: [:show]
  resources :incidents do
    get :sign, to: 'incidents#confirmation'
    post :sign, to: 'incidents#sign'
  end
  resources :report_incidents, only: [:new, :create]
  resources :positions, except: [:show]
  resources :patients, except: [:show] do
    resources :appointments, except: [:show], controller: 'patients/appointments'
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  username               :string           default(""), not null
#  name                   :string
#  siape                  :integer
#  sector_id              :integer
#  position_id            :integer
#  avatar                 :string
#  course_id              :integer
#  admin                  :boolean          default(FALSE)
#

class User < ApplicationRecord
  mount_uploader :avatar, UserUploader
  include SearchCop

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
         :validatable

  # Validações
  validates :username, :sector, presence: true

  # Delegates
  delegate :initial, to: :sector, prefix: true

  # Associações
  has_many :permissions, dependent: :destroy
  belongs_to :sector
  belongs_to :position
  belongs_to :course, optional: true

  # Nested form
  accepts_nested_attributes_for :permissions

  # Atributos para busca com SearchCop
  search_scope :search do
    attributes :name, :email, :siape
    attributes :sector => "sector.initial"
  end

  # Retorna um vetor com os atributos que serão utilizados para a
  # busca nas listagens de usuários
  #
  # @return [Array] contendo os atributos para a busca
  def self.ordenation_attributes
    [["ID",'id'], ["Nome",'name']]
  end

  # Retorna um vetor com os atributos que serão utilizados para a
  # busca nas listagens de usuários
  #
  # @return [Array] contendo os atributos para a busca
  def self.get_by_position(name_position)
    Position.find_by_name(name_position).users.collect {|p| [ p.name, p.id ] }
  end

  # Verifica se o usuário selecionado é o usuário que esta logado
  #
  # @param [Object User] current_user
  # @return [Boolean] true se o usuário for igual ao usuário logo
  # @return [Boolean] false se o usuário for diferente ao usuário logo
  def is_current?(current_user)
    current_user.id == id ? true : false
  end

  # Retorna um vetor contendo os nomes e seus respectivos IDs
  #
  # @return [Array] contendo nomes e seus IDs
  def self.get_all
    order('name asc').collect {|p| [ p.name, p.id ] }
  end

  def last_access
    updated_at.strftime('%d/%m/%Y %H:%M')
  end

  # Verifica se o usuário faz parte de um determinado sertor
  #
  # @param [String] _sector
  # @return [Boolean] true se o usuário faz parte do sertor
  # @return [Boolean] false se o usuário não faz parte do setro
  def it_is_part_of_the_sector?(*_sectors)
    _sectors.each do |_sector|
      if sector.initial.downcase == _sector
        return true
      end
    end
    return false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ParamsSearch

  load_and_authorize_resource
  skip_authorize_resource only: [:change_password, :update]

  before_action :set_user, only: [:edit, :destroy, :update]
  add_breadcrumb "Home", :root_path

  def index
    add_breadcrumb "Serti", sector_actions_path('serti')
    add_breadcrumb "Usuários"

    @users = User.order("#{set_order}": :desc)
                 .search(params[:search])
                 .page(params[:page])
  end

  def new
    add_breadcrumb "Serti", sector_actions_path('serti')
    add_breadcrumb "Usuários", :users_path
    add_breadcrumb "Novo usuário"

    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, flash: { success: 'Usuário cadastrado com sucesso' }
    else
      flash.now[:error] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    add_breadcrumb "Serti", sector_actions_path('serti')
    add_breadcrumb "Usuários", :users_path
    add_breadcrumb "Atualizar usuário"
  end

  def update
    if @user.update(check_password(user_params))
      redirect_to users_path, flash: { success: 'Usuário atualizado com sucesso' }
    else
      flash.now[:error] = @user.errors.full_messages
      render commit_action(params[:commit])
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "Usuário deletado com sucesso"
      redirect_back(fallback_location: users_path)
    else
      flash.now[:error] = @user.errors.full_messages
      render :new
    end
  end

  def change_password
    @user = current_user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def check_password(user_params)
    if user_params[:password].empty?
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
      user_params
    else
      user_params
    end
  end

  def commit_action(commit)
    return :change_password if commit == "Trocar senha"
    return :edit if commit == "Salvar"
  end

  def user_params
    params.require(:user).permit(
      :name, :siape, :sector_id, :position_id, :username, :email, :password,
      :password_confirmation, :status, :avatar, :course_id, :admin
    )
  end
end

app/views/users/_form.html.erb
<%= form_for user do |f| %>
  <fieldset>
    <legend>Dados pessoais</legend>
    <div class="field is-horizontal">
      <div class="field-body">
        <div class="field">
          <p class="control">
            <%= f.label :name, 'Nome', class: 'label' %>
            <%= f.text_field :name, class: 'input is-medium', placeholder: 'Nome', required: true %>
          </p>
        </div>
        <div class="field">
          <%= f.label :avatar, 'Imagem', class: 'label' %>
          <div class="file is-medium is-success">
            <label class="file-label">
              <%= f.file_field :avatar, class: 'file-input' %>
              <span class="file-cta">
                <span class="file-icon">
                  <i class="fa fa-upload"></i>
                </span>
                <span class="file-label">
                  Selecione uma imagem
                </span>
              </span>
            </label>
          </div>
        </div>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Dados Institucionais</legend>
    <div class="field is-horizontal">
      <div class="field-body">
        <div class="field">
          <p class="control">
            <%= f.label :email, class: 'label' %>
            <%= f.email_field :email, class: 'input is-medium', placeholder: 'Email', required: true %>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <%= f.label :siape, class: 'label' %>
            <%= f.text_field :siape, class: 'input is-medium', placeholder: 'SIAPE', required: true %>
          </p>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-body">
        <div class="field">
          <%= f.label :sector_id, 'Setor', class: 'label' %>
          <p class="control">
            <span class="select is-medium">
              <%= f.select :sector_id, Sector.initials, { prompt: "Selecione o setor" }, { :class => "select2" } %>
            </span>
          </p>
        </div>
        <div class="field">
          <%= f.label :position_id, 'Cargo/Função', class: 'label' %>
          <p class="control">
            <span class="select is-medium">
              <%= f.select :position_id, Position.get_all, { prompt: "Selecione o cargo" }, { :class => "select2" } %>
            </span>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <%= f.label :course_id, "Coordenador?", class: 'label' %>
            <span class="select is-medium">
              <%= f.select :course_id, Course.initials, { prompt: "Curso Coordenado" }, { :class => "select2" } %>
            </span>
          </p>
        </div>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Dados de acesso</legend>
    <div class="field is-horizontal">
      <div class="field-body">
        <div class="field">
          <p class="control">
            <%= f.label :username, 'Usuário', class: 'label' %>
            <%= f.text_field :username, class: 'input is-medium', placeholder: 'Usuário', required: true %>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <%= f.label :password, 'Senha', class: 'label' %>
            <%= f.password_field :password, class: 'input is-medium', placeholder: 'Senha' %>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <%= f.label :password_confirmation, 'Repetir senha', class: 'label' %>
            <%= f.password_field :password_confirmation, class: 'input is-medium', placeholder: 'Confimação senha' %>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <%= f.label :admin, 'Admin?', class: 'label' %>
            <%= f.check_box :admin %>
          </p>
        </div>
      </div>
    </div>
  </fieldset>

  <div class="margin-top-20px">
    <p class="control">
      <%= f.submit "Salvar", class: "button is-success is-medium in-mobile-expand"%>
    </p>
  </div>
<% end %>

app/views/users/change_password.html.erb
<div class="content">
  <h1 class="title is-3">Trocar senha</h1>
  <%= form_for @user do |f| %>
    <fieldset>
      <legend>Senha para acesso</legend>
      <div class="field is-horizontal">
        <div class="field-body">
          <div class="field">
            <p class="control">
              <%= f.label :password, 'Senha', class: 'label' %>
              <%= f.password_field :password, class: 'input is-medium', placeholder: 'Senha', required: true %>
            </p>
          </div>
          <div class="field">
            <p class="control">
              <%= f.label :password_confirmation, 'Repetir senha', class: 'label' %>
              <%= f.password_field :password_confirmation, class: 'input is-medium', placeholder: 'Confimação senha', required: true %>
            </p>
          </div>
        </div>
      </div>
    </fieldset>

    <div class="margin-top-20px">
      <p class="control">
        <%= f.submit "Trocar senha", class: "button is-success is-medium in-mobile-expand"%>
      </p>
    </div>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class="content">
  <h1 class="title is-3">Atualizar usuário</h1>
  <%= render 'form', user: @user %>
</div>

app/views/users/index.html.erb
<div class="columns">
  <div class="column">
    <% if can? :create, User %>
      <%= link_to new_user_path, class: "button is-success in-mobile-expand" do %>
        <span class="icon">
          <i class="ion-plus-round"></i>
        </span>
        <span>Novo Usuário</span>
      <% end %>
    <% end %>
  </div>
  <div class="column">
    <% show_search_error_message(@users, params) %>
    <%= render 'layouts/search', path: users_path, v: attr_order(@users) %>
  </div>
</div>

<table class="table is-striped is-fullwidth">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>SIAPE</th>
      <th>Setor</th>
      <th>Acessado em?</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.siape %></td>
      <td><%= user.sector_initial %></td>
      <td><%= user.last_access %></td>
      <td class="has-text-right">
        <div class="dropdown">
          <span class="button is-danger in-mobile-expand">Ações</span>
          <div class="dropdown-content">
            <% if can? :update, User %>
              <%= link_to edit_user_path(user), class: 'button is-success in-mobile-expand' do %>
                <span class="icon">
                  <i class="ion-edit"></i>
                </span>
                <span>Editar</span>
              <% end %>
            <% end %>
            <% if can? :read, Permission %>
              <%= link_to user_permissions_path(user), class: 'button is-success in-mobile-expand' do %>
                <span class="icon">
                  <i class="ion-edit"></i>
                </span>
                <span>Permissões</span>
              <% end %>
            <% end %>
            <% if can? :destroy, User %>
              <%= link_to user_path(user), method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class: 'button is-danger in-mobile-expand', disabled: user.is_current?(current_user) do %>
                <span class="icon">
                  <i class="ion-close"></i>
                </span>
                <span>Excluir</span>
              <% end %>
            <% end %>
          </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/users/new.html.erb
<div class="content">
  <h1 class="title is-3">Cadastrar usuário</h1>
  <%= render 'form', user: @user %>
</div>